options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/fine-climber-412705/cicd2/python-image:latest', './app1' ]
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/fine-climber-412705/cicd2/python-image:latest' ]
  id: 'Push Docker Image'

  #images:
   #- 'us-central1-docker.pkg.dev/${PROJECT_ID}/cicdtest/python-image:latest'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Get GKE credentials'
    args:
      - 'gcloud'
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-cluster'  # Name of your GKE cluster
      - '--zone'
      - 'us-central1-a'  # Zone where your cluster is located

  # Step 4: Apply Kubernetes deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to GKE'
    args:
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'kubernetes/app1.yaml'  # Path to your Kubernetes deployment YAML file

  # Step 5: Optionally, apply a Kubernetes service (if needed)
  #env:
   # - 'PROJECT_ID = fine-climber-412705'


